#:schema node_modules/wrangler/config-schema.json
name = "todo"
compatibility_date = "2024-11-06"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "todo"
database_id = "c5d0584a-46df-4d0b-98b0-796949a53e85"
